name: yaru_example
description: Demonstrate yaru
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  collection: ^1.19.1
  connectivity_plus: ^7.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  handy_window: ^0.4.2
  http: ^1.6.0
  path: ^1.9.1
  safe_change_notifier: ^0.4.0+1
  url_launcher: ^6.3.2
  watch_it: ^2.4.2
  yaru:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  dbus:
    git: https://github.com/kumsumit/dbus.dart.git

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: YaruIcons
      fonts:
        - asset: ../assets/yaru_icons.otf
